name: ✨ 功能建议
description: 建议一个新功能
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！您的建议有助于让PadCast变得更好。

  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 描述现有的问题或不便之处
      placeholder: 我遇到的问题是...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: 解决方案
      description: 详细描述您希望的功能
      placeholder: 我希望能够...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 描述您考虑过的替代解决方案
      placeholder: 我也考虑过...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 这个功能对您有多重要？
      options:
        - 低 (有就更好)
        - 中 (会显著改善体验)
        - 高 (非常需要)
        - 紧急 (阻碍正常使用)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 功能类别
      description: 这个功能属于哪个类别？
      options:
        - 网络连接
        - 音视频播放
        - 用户界面
        - 性能优化
        - 设置配置
        - 兼容性
        - 安全性
        - 其他
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: 使用场景
      description: 描述这个功能的具体使用场景
      placeholder: |
        场景1: 当我...时，我希望能够...
        场景2: 在...情况下，这个功能可以...

  - type: textarea
    id: technical-considerations
    attributes:
      label: 技术考虑
      description: 如果您有技术背景，请分享相关的技术考虑
      placeholder: 可能需要考虑的技术问题...

  - type: checkboxes
    id: related-features
    attributes:
      label: 相关功能
      description: 这个功能可能影响哪些现有功能？
      options:
        - label: AirPlay连接
        - label: 音视频同步
        - label: 网络监控
        - label: 性能监控
        - label: 用户设置
        - label: 自动化测试
        - label: 不确定

  - type: textarea
    id: additional-context
    attributes:
      label: 其他信息
      description: 添加任何其他相关信息、截图或参考资料
      placeholder: 其他可能有用的信息...

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 在提交之前，请确认以下事项
      options:
        - label: 我已经搜索了现有的issues，确认这个功能尚未被建议
          required: true
        - label: 我已经阅读了项目的roadmap和文档
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true